### ISSUE TITLE
failed to load

### ISSUE THREAD

**Issue by tsvetann** [tobiaslins/frappe-charts-react-example#1]
I copied your example but it failed with the following error:

<img width="763" alt="screen shot 2017-11-06 at 16 17 41" src="https://user-images.githubusercontent.com/2565891/32449906-1c8d3d7c-c313-11e7-9706-8f02c1143f96.png">

Have i missed anything?
Thx

**Comment by tobiaslins** [comment]
Did you use the whole example or just the chart.js part?

It's important to use the fork or current version of `frappe-charts` (the current version on NPM is not supporting react yet)

Can you show me your package.json please?
@tsvetann

**Comment by coryshaw** [comment]
I'm having the same issue. I'm pulling down your fork via 

```"frappe-charts": "tobiaslins/charts#support-react",```

then, using your example in chart.js, you import via

```import Frappe from 'frappe-charts'```

however, in the node_modules folder, it looks like this
![screen shot 2017-11-06 at 4 28 02 pm](https://user-images.githubusercontent.com/116262/32469392-b31e28ae-c30f-11e7-889e-ce068dab27e0.png)

and there's no function called `Frappe`...only `Chart` in `frappe-charts.min.iife.js`.

Any ideas? Thanks!!

**Comment by tobiaslins** [comment]
It is because you have already a newer version of `frappe-charts` included in your `package.json`

I just checked out the example and everything is working fine. I'll update the example soon, if they will release my modifications for react support!

**Comment by tobiaslins** [comment]
I just updated the example. 
Please just import `import Frappe from 'frappe-charts/dist/frappe-charts.min.esm'` 
now and  install the latest NPM dependency from `frappe-charts`

@coryshaw

**Comment by tsvetann** [comment]
@tobiaslins the latest npm dep works for me

**Comment by coryshaw** [comment]
@tobiaslins awesome, works like a charm, thanks a lot. I'm looking forward to digging into this great chart lib!
